[project]
name = "rag-experiment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "chromadb>=1.0.10",
    "jieba>=0.42.1",
    "llama-index",
    "ollama>=0.4.8",
]
